api: Update API schema to Layer 162
Squashed commit of the following:

commit 5fd5fc737b3ffeef6ef1536864875f391a5fac4d
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Mon Sep 4 17:47:55 2023 +0200

    Update to Layer 162

commit 2737c8b60779edb7f7689c47a6f9303305a4a9fd
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Aug 15 06:10:17 2023 +0200

    fixes

commit 53ae80ec215b0d4c911aa3f3d8b8096feb24b2e7
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Aug 15 06:06:01 2023 +0200

    add some more errors

commit 80299a672344fbe924e41abacaee265412129fdd
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Aug 15 05:57:59 2023 +0200

    Add new error @ 2023-07-26 18:31:05.980970

commit 911435c024cc72d405b596dde493cd426cf26485
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Aug 15 05:55:02 2023 +0200

    Update API to Layer 161

commit 7e8ff33f4529796857d17102a948bd1677b93098
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Jul 25 02:03:40 2023 +0200

    Fix conditions

commit 42bae1e0c9a7258f226555f5048c4d9dd5b249ed
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Jul 25 01:43:29 2023 +0200

    https://t.me/pyrogramchat/576317

commit 50a2deda69ab99b97dfec583d4d28a0fb06f85b1
Merge: 52a52284 7c6e678d
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Tue Jul 25 01:42:56 2023 +0200

    Merge branch 'moshe-coh-patch-3' into L160

commit 7c6e678dd7fb70eae793db80fc0ad8db6cc80dcf
Author: Moshe <62907797+moshe-coh@users.noreply.github.com>
Date:   Mon Jul 24 14:56:40 2023 +0300

    Update message.py

    AttributeError: 'MessageReplyStoryHeader' object has no attribute 'reply_to_msg_id'
    fixed

commit 52a52284a3ed56ae8094033394d8c8661a6b44ac
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Sat Jul 22 06:07:06 2023 +0200

    https://t.me/TelethonChat/554047

commit 2b29dad699251d73f9613c6a3a3b857cbb44ab58
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Fri Jul 21 17:53:08 2023 +0200

    sendMessage reply_to changes

commit fc9e99aedeb56faf669f9da37ebc7a208a29955e
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Fri Jul 21 17:49:38 2023 +0200

    https://t.me/pyrogramchat/575221

commit 836d8561fe5c16c5c053d8945de7d85b48dcd03e
Author: shriMADhav U k <hetzner@shrimadhavuk.me>
Date:   Fri Jul 21 17:33:08 2023 +0200

    Update API to Layer 160

    https://github.com/telegramdesktop/tdesktop/raw/dev/Telegram/SourceFiles/mtproto/scheme/api.tl
    https://github.com/telegramdesktop/tdesktop/raw/dev/Telegram/SourceFiles/mtproto/scheme/layer.tl